title: The most awesome title
email: rolandmaio38@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What what!
  Yes please!
baseurl: ""
url: ""

# Build settings
theme: jekyll-theme-hacker
gems:
  - jekyll-feed
